# ci脚本的名称
name: gh_pages_deploy
# 触发的时机
on:
  # 在push阶段触发
  push:
    # 对应的分支
    branches: [ main ]
  # 在PR阶段触发
  pull_request:
    # 对应的分支
    branches: [ main ]
# 执行的任务
jobs:
  # 任务名称
  build:
    # 执行的环境，默认是在最新版本的Ubuntu系统
    runs-on: ubuntu-latest
    # 执行的步骤
    steps:
      # checkout代码
      # 其中actions是github官方账号，checkout是改账号下提供的库，可以直接拿来使用，对应的版本是v2
      # setup-node同上
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        # 设置node的版本
        with:
          node-version: '14'
        # 执行步骤的名称
      - name: Compiling start
        # 执行的具体脚本
        run: echo Compiling start!
        # 如果在执行的时候报错，提示需要用户名跟邮箱，那么需要单独设置下邮箱跟用户名
      - run: git config --global user.email "1642114555@qq.com"
      - run: git config --global user.name "alexzhang1030"
        # 执行安装跟打包命令
      - run: npm install && npm run docs:build
      - name: Deploy
        # 这个是第三方提供的库，可以推送打包后的内容到指定分支
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 这边需要设置第二步获取到的deploy key，否则会提示没有权限推送代码
          deploy_key: ${{ secrets.gh_deploy }}
          # 推送到该仓库中，地址格式为github名称/仓库名
          external_repository: alexzhang1030/vue3-developer-guide
          # 推送的分支
          publish_branch: gh_pages
          # 推送的内容
          publish_dir: docs/.vuepress/dist
